using Korp.Faturamento.API.Data;
using Korp.Faturamento.API.DTOs;
using Korp.Faturamento.API.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Korp.Faturamento.API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class NotaFiscalController : ControllerBase
    {
        private readonly FaturamentoDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly ILogger<NotaFiscalController> _logger;

        // Configurable parameters
        private const int PRINT_RETRY_COUNT = 3;
        private const int PRINT_BACKOFF_MS = 150;
        private static readonly TimeSpan IDEMPOTENCY_EXPIRES = TimeSpan.FromHours(1);
        private static readonly System.Text.Json.JsonSerializerOptions JsonOptions = new(System.Text.Json.JsonSerializerDefaults.Web);

        public NotaFiscalController(FaturamentoDbContext context, IHttpClientFactory httpClientFactory, ILogger<NotaFiscalController> logger)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _logger = logger;
        }

        [HttpPost]
        public async Task<IActionResult> CriarNota([FromBody] CriarNotaFiscalDto dto)
        {
            // Simple idempotency by X-Idempotency-Key header
            var idempotencyKey = Request.Headers["X-Idempotency-Key"].FirstOrDefault();
            var requestBody = System.Text.Json.JsonSerializer.Serialize(dto);
            var requestHash = System.BitConverter.ToString(System.Security.Cryptography.SHA256.HashData(System.Text.Encoding.UTF8.GetBytes(requestBody))).Replace("-", "");
            var requestHeaders = string.Join(';', Request.Headers.Select(h => h.Key + ":" + string.Join(',', h.Value)));

            if (!string.IsNullOrEmpty(idempotencyKey))
            {
                var existing = await _context.IdempotencyEntries
                    .FirstOrDefaultAsync(e => e.Key == idempotencyKey && e.Route == "criarNota");
                if (existing != null)
                {
                    if (existing.ExpiresAt != null && existing.ExpiresAt < DateTime.UtcNow)
                    {
                        // expired - allow re-execution
                        // fallthrough
                    }
                    else if (!string.IsNullOrEmpty(existing.RequestHash) && existing.RequestHash != requestHash)
                    {
                        return Conflict(ApiResponse.Error(409, "Idempotency key reused with different payload."));
                    }
                    else
                    {
                        return new ContentResult
                        {
                            StatusCode = existing.ResponseStatus,
                            Content = existing.ResponseBody,
                            ContentType = "application/json"
                        };
                    }
                }
            }

            try
            {
                var itensAgrupados = dto.Itens
                    .GroupBy(i => i.ProdutoId)
                    .Select(g => new NotaFiscalItem
                    {
                        ProdutoId = g.Key,
                        Quantidade = g.Sum(i => i.Quantidade)
                    })
                    .ToList();

                var notaFiscal = new NotaFiscal
                {
                    // NumeroSequencial is generated by the database (ValueGeneratedOnAdd)
                    Status = StatusNota.Aberta,
                    DataCriacao = DateTime.UtcNow,
                    Itens = itensAgrupados
                };

                _context.NotasFiscais.Add(notaFiscal);
                await _context.SaveChangesAsync();

                var responseEnvelope = ApiResponse.Created("Nota fiscal criada com sucesso.", notaFiscal);
                var responseBody = System.Text.Json.JsonSerializer.Serialize(responseEnvelope, JsonOptions);

                if (!string.IsNullOrEmpty(idempotencyKey))
                {
                    _context.IdempotencyEntries.Add(new Models.IdempotencyEntry
                    {
                        Key = idempotencyKey,
                        Route = "criarNota",
                        RequestHash = requestHash,
                        RequestHeaders = requestHeaders,
                        ResponseStatus = 201,
                        ResponseBody = responseBody,
                        ExpiresAt = DateTime.UtcNow.AddHours(1)
                    });
                    await _context.SaveChangesAsync();
                }

                return CreatedAtAction(nameof(ObterNota), new { id = notaFiscal.Id }, responseEnvelope);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Erro interno ao criar a nota fiscal.");
                return StatusCode(500, ApiResponse.Error(500, "Erro interno ao criar a nota fiscal."));
            }
        }

        [HttpGet]
        public async Task<IActionResult> ListarTodas()
        {
            var notas = await _context.NotasFiscais
                .Include(n => n.Itens)
                .ToListAsync();

            return Ok(ApiResponse.Ok("Notas fiscais listadas com sucesso.", notas));
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> ObterNota(int id)
        {
            var nota = await _context.NotasFiscais
                .Include(n => n.Itens)
                .FirstOrDefaultAsync(n => n.Id == id);

            if (nota == null) return NotFound(ApiResponse.Error(404, "Nota fiscal não encontrada."));

            return Ok(ApiResponse.Ok("Nota fiscal obtida com sucesso.", nota));
        }

        [HttpPost("{id}/imprimir")]
        public async Task<IActionResult> ImprimirNota(int id)
        {
            // Idempotency for printing: include note id to make the operation unique
            var idempotencyKey = Request.Headers["X-Idempotency-Key"].FirstOrDefault();
            var routeKey = !string.IsNullOrEmpty(idempotencyKey) ? $"imprimir:{id}:{idempotencyKey}" : null;

            if (!string.IsNullOrEmpty(routeKey))
            {
                var existing = await _context.IdempotencyEntries
                    .FirstOrDefaultAsync(e => e.Key == routeKey && e.Route == "imprimir");
                if (existing != null)
                {
                    return new ContentResult
                    {
                        StatusCode = existing.ResponseStatus,
                        Content = existing.ResponseBody,
                        ContentType = "application/json"
                    };
                }
            }

            var nota = await _context.NotasFiscais
                .Include(n => n.Itens)
                .FirstOrDefaultAsync(n => n.Id == id);

            if (nota == null)
                return NotFound(ApiResponse.Error(404, "Nota fiscal não encontrada."));

            if (nota.Status != StatusNota.Aberta)
                return BadRequest(ApiResponse.Error(400, "Apenas notas com status 'Aberta' podem ser impressas."));

            try
            {
                var estoqueClient = _httpClientFactory.CreateClient("EstoqueClient");

                var succeeded = new List<NotaFiscalItem>();

                // Best-effort compensation: reverses stock already baixado for succeeded items.
                async Task CompensarItens()
                {
                    foreach (var s in succeeded)
                    {
                        var estornarPayload = new { ProdutoId = s.ProdutoId, Quantidade = s.Quantidade };
                        try
                        {
                            var estornarReq = new HttpRequestMessage(HttpMethod.Post, "/api/estoque/estornar")
                            {
                                Content = System.Net.Http.Json.JsonContent.Create(estornarPayload)
                            };
                            if (!string.IsNullOrEmpty(idempotencyKey))
                            {
                                estornarReq.Headers.Add("X-Idempotency-Key", $"{idempotencyKey}-nota-{nota.Id}-item-{s.ProdutoId}-estorno");
                            }
                            await estoqueClient.SendAsync(estornarReq);
                        }
                        catch { /* swallow - best effort */ }
                    }
                }

                foreach (var item in nota.Itens)
                {
                    var payload = new { ProdutoId = item.ProdutoId, Quantidade = item.Quantidade };
                    bool itemOk = false;

                    // Retry loop for concurrency conflicts
                    for (int attempt = 0; attempt < 3 && !itemOk; attempt++)
                    {
                        var request = new HttpRequestMessage(HttpMethod.Post, "/api/estoque/baixar")
                        {
                            Content = System.Net.Http.Json.JsonContent.Create(payload)
                        };

                        // propagate idempotency key, make it unique per nota/item
                        if (!string.IsNullOrEmpty(idempotencyKey))
                        {
                            request.Headers.Add("X-Idempotency-Key", $"{idempotencyKey}-nota-{nota.Id}-item-{item.ProdutoId}");
                        }

                        var response = await estoqueClient.SendAsync(request);

                        if (response.IsSuccessStatusCode)
                        {
                            itemOk = true;
                            succeeded.Add(item);
                            break;
                        }

                        if (response.StatusCode == System.Net.HttpStatusCode.Conflict)
                        {
                            // concurrency conflict - small backoff then retry
                            await Task.Delay(150 * (attempt + 1));
                            continue;
                        }

                        // other errors - abort
                        var erroEstoque = await response.Content.ReadAsStringAsync();

                        // compensate any succeeded items
                        await CompensarItens();

                        return BadRequest(ApiResponse.Error(400, $"Falha ao baixar estoque do Produto ID {item.ProdutoId}. {erroEstoque}"));
                    }

                    if (!itemOk)
                    {
                        // after retries still not ok - compensate and return
                        await CompensarItens();

                        return Conflict(ApiResponse.Error(409, $"Não foi possível reservar/baixar estoque para o Produto ID {item.ProdutoId} após tentativas."));
                    }
                }

                nota.Status = StatusNota.Fechada;
                await _context.SaveChangesAsync();

                var successEnvelope = ApiResponse.Ok("Nota fiscal impressa e fechada com sucesso!", new { notaId = nota.Id, status = nota.Status.ToString() });
                var successResp = System.Text.Json.JsonSerializer.Serialize(successEnvelope, JsonOptions);

                if (!string.IsNullOrEmpty(routeKey))
                {
                    _context.IdempotencyEntries.Add(new Models.IdempotencyEntry
                    {
                        Key = routeKey,
                        Route = "imprimir",
                        RequestHash = "", // already tied to note/idempotency combination
                        RequestHeaders = "",
                        ResponseStatus = 200,
                        ResponseBody = successResp,
                        ExpiresAt = DateTime.UtcNow.Add(IDEMPOTENCY_EXPIRES)
                    });
                    await _context.SaveChangesAsync();
                }

                return Ok(successEnvelope);
            }
            catch (HttpRequestException)
            {
                return StatusCode(503, ApiResponse.Error(503, "O serviço de estoque está temporariamente indisponível. A impressão foi cancelada."));
            }
            catch (Polly.CircuitBreaker.BrokenCircuitException)
            {
                return StatusCode(503, ApiResponse.Error(503, "O serviço de estoque está temporariamente indisponível. A impressão foi cancelada."));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Erro interno durante a impressão da nota {NotaId}.", id);
                return StatusCode(500, ApiResponse.Error(500, "Erro interno durante a impressão."));
            }
        }
    }
}